apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: wordpress
type: Opaque
stringData:
    mysql-password_unencrypted: ENC[AES256_GCM,data:+YsQXzvl,iv:sFKm8KbLR3ZFHGd7zgiwv1Iy8pc+7FDLLQDiCNqzsk0=,tag:FFBZ3LyyNeNNMrhGD02sFg==,type:str]
    mysql-root-password_unencrypted: ENC[AES256_GCM,data:RF58IWQWNE0=,iv:4ewQ2uicMbYCL/Nlc346kA97BVWjvQvLbgFyyuluxls=,tag:stQxDX2WKC4af1qN2WiPNg==,type:str]
    mysql-username_unencrypted: ENC[AES256_GCM,data:3kJZ0dVu,iv:ixUdl8YEfflgAngPcNyF2PT8fuFjzn63vGu1a1RTGHk=,tag:hZpfBo3cIxveIDWkCWhiHg==,type:str]
sops:
    age:
        - recipient: age14mfhdkwqtwuvqmpygvkv77qzkwtkkk7zycfrxr7jnx89ss23q34s59rpfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VGV1OWNoQlV5MlQyQk83
            S0pmM0F1UDZqMUpLMFhwRjVlK3hTVmxRWjEwCm9mbEp0SUJkSDZrRmVkTXkwcFdH
            QUZRTHI4ODAvQVZlNmt5UWI5RHBwajQKLS0tIHUva01JWkNQNVArNWVOazNXSk5X
            azlubFN4NjNqc0x4YjlHOFN4RXJkSUUK3K312LpPWIjjbEfAS3DIldquHUBnJQFD
            ttGP0/J6fjcaRugrCvms3d3uEW38ShPDtWihZO/peryDgp+A8DzRig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T07:36:25Z"
    mac: ENC[AES256_GCM,data:JHtwlXy8zto3xB0IF1o8UrIyyamN6BCTLPeWGzPZWALc/hppsshdOOaF82ciu/FY+5gMW/Is6Tvc5lCRALsmqthr4N7FtBumf10QspxS1Hrv6PwJzSVyMaKoCjpDPh6sSAjhri/RgAWl+AIj33F3Evq3hxq0XLmqpD+kgiLYBtc=,iv:viyiNqmYAGo/m5Ws69u3yq1N8BlixoXkxkCGeVNOjBQ=,tag:ExCwEkNNZpLrGBjd/XaCcA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
