apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: wordpress
type: Opaque
stringData:
    mysql-root-password_unencrypted: ENC[AES256_GCM,data:rQc029dMEi8=,iv:+aa/b7NE+hcz9HyrgfRxyVuifsgNSaS0lbSbJLfNK6c=,tag:9wPyvclnBm3Nj3znHPa22A==,type:str]
    mysql-password_unencrypted: ENC[AES256_GCM,data:+9sq65xV,iv:m1C9GPi70QqnIbxIejGyd20xbUM1oqadRYfn1jixnm4=,tag:NMgS7L+BX/bvDJ9Q6ek8eg==,type:str]
sops:
    age:
        - recipient: age14mfhdkwqtwuvqmpygvkv77qzkwtkkk7zycfrxr7jnx89ss23q34s59rpfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbUhyOHJ1RGJLQmFkUEpI
            eUk1dzVEREplVHNNZXFPZzhNbEhFdkVreTJNCm1KcWRsdDNZZ1RtZmM5SGg3aVo5
            aXVOUkFzUHJOWndBZFhOL1lCblhKTmcKLS0tIFU2dnE4aHNnWWFHWC9xa2RDcUVT
            czVsc3MxZktZNDU3bCtqNTBOQTRUbUEKNDp8gyRCOuedOW0RIUcYgbLvQtEXyEFg
            cdnlQFstX6EIkK4Z0bmEQd2jYZc7XaChbSoQX/IdCT5EGTrTmzjyaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T08:09:05Z"
    mac: ENC[AES256_GCM,data:3oYgh2W9qou7tFtpgHsKGnOwbYCcOBmCLFsYvOvXVzhJNtmwagzejRGuoS9+LN9FfBKUfFyfOg7isLJ5KZN8c5k+Lj0v6bsMQXtP3CSaG/pyOSRP1LE6rgYNJJmKxprdN5F0gbhvov3yE1E8WZsxGYnkImD55E619cVNrxi3Uso=,iv:re5wxOjTfj/94Ayrk2Hxg3nOsqFaAGR0qgvZR/7WJQU=,tag:JXQvbLc1+DcBCD/ceb/AHg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
