apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 172.18.255.200-172.18.255.250

