apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 56.6.0   # stable version
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      adminUser: admin
      adminPassword: admin123
      service:
        type: LoadBalancer
      ingress:
        enabled: true
        hosts:
          - grafana.local

    prometheus:
      service:
        type: LoadBalancer
      ingress:
        enabled: true
        hosts:
          - prometheus.local

    alertmanager:
      service:
        type: LoadBalancer
      ingress:
        enabled: true
        hosts:
          - alertmanager.local
